In [ ]:
import numpy as np
import pandas as pd


In [ ]:
from sklearn import datasets
boston = datasets.load_boston(return_X_y=False)

In [ ]:
# print(boston)
X = boston.data
Y = boston.target

X = np.array(X)
y = np.array(Y)

print(X)
print(Y)


[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_rem, Y_train, Y_rem = train_test_split(X,Y, train_size=0.3)
X_valid, X_test, Y_valid, Y_test = train_test_split(X_rem,Y_rem, test_size=0.85)


In [ ]:
class Gradient_Regression():

  def __init__(self,learning_rate,rho,epochs):
    self.lr = learning_rate
    self.iteration = epochs
    self.rho = rho
    self.jw = 0

  def train(self,xdata,ydata):
    self.p = len(xdata)
    self.f = len(xdata.ndim)
    self.X = xdata
    self.Y = ydata
    self.w = np.ones(self.f)
    self.c = 1
    
    
    for i in range(self.iteration) :
      self.update_weights()

    return self

  def update_weights(self):
    ypred = self.predict_Y(self.X)
    current_jw = self.calculate_mse(ypred,self.Y)
    Convergennce(current_jw,self.rho)
    dw = self.lr*((self.X).dot(ypred-self.Y)/self.p)
    dc =  self.lr*(np.sum(ypred-self.Y)/self.p)
    self.w = w-dw
    self.c = c-dc
    
    return self

  def Convergence(self,current_jw,rho){
     self.jw = current_jw 
  }

  def predict_Y(self, xdata):
    return xdata.dot(self.w)+self.c

  def calculate_mse(self,ypred,y):
    return np.square(np.sum(ypred-y))/(2*self.p)

In [ ]:
hyperparameter = [[0.1, 0.5, 10], [0.01, 0.6, 20], [0.02, 0.7, 30], [0.03, 0.8, 40], [0.001, 0.9, 50]]

In [ ]:
for x in  hyperparameter :
  print(x[0],x[1],x[2])
  Gr = Gradient_Regression(x[0],x[1],x[2])
  values = Gr.train(X_valid,Y_valid)
  print(values.jw)

0.1 0.5 10


TypeError: ignored