In [1]:
import numpy as np

In [2]:
myarr = np.array([5,56,8,7],np.int64)

In [3]:
myarr[2]

8

In [4]:
myarr.shape #shape

(4,)

In [5]:
myarr.dtype

dtype('int64')

**Array Creation**


In [6]:
zeros = np.zeros((2,6))

In [7]:
zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [8]:
rng = np.arange(20)

In [9]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
ones = np.ones(10)


In [11]:
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
t = np.arange(3,10,2) #+2 iterator

In [13]:
t

array([3, 5, 7, 9])

In [14]:
 rndm = np.random.normal(0,1,1)

In [15]:
rndm

array([-1.44855389])

In [16]:
rdd = np.random.rand()

In [17]:
rdd

0.11002116746431323

In [20]:
rd = np.random.rand(1,1)*5 +10



In [21]:
rd

array([[12.26420766]])