In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.utils import shuffle
from sklearn.metrics import accuracy_score
import random

In [ ]:
def predict(xtest,ytest,weight):
  ypred = np.ones(ytest.shape[0])
  hypo = np.dot(xtest,weight)
  print(hypo)

  for i in range(0,hypo.shape[0]-1):
    if(hypo[i] >=0.5):
      ypred[i] = 1
    if(hypo[i] <0.5):
      ypred[i] = 0

  test_acc = accuracy_score(ytest,ypred)
  return test_acc


def add_intercept(xtrain):
  intercept = np.ones((xtrain.shape[0],1))
  # print(intercept)
  # print(np.concatenate((intercept,xtrain),axis=1))
  return np.concatenate((intercept,xtrain),axis=1);

def perceptron(xtrain,ytrain,same_weight):
  xtrain = add_intercept(xtrain)
  used_index = []
  weight = np.zeros(xtrain.shape[1])

  for i in range(0,xtrain.shape[1]):
    weight[i] = 0.1
  index = random.randint(0,xtrain.shape[0]-1)
  xtrain,ytrain = shuffle(xtrain,ytrain)
  used_index.append(index)
  epoch = 1
  converged = False
  while not converged:
    print("epoch",epoch)
    hypothesis = np.dot(xtrain[index],weight)
    if(ytrain[index] > 0 and hypothesis < 0):
      weight = weight + xtrain[index]

    if(ytrain[index] < 0 and hypothesis >0):
      weight = weight - xtrain[index]

    index = random.randint(0,xtrain.shape[0]-1)
    used_index.append(index)

    if(len(set(used_index)) == xtrain.shape[0]):
      # check accuracy
      score = predict(xtrain,ytrain,weight)
      if(score*100 == 100):
        print("succesfully converged")
        converged = True
      epoch = epoch+1
  
  return weight
    

     

  

In [ ]:
x_train = np.array([[0,1],[1,1],[0,0],[1,0]])
print(x_train)
y_train = np.array([1, 1, 0, 1])
print(y_train)
weight = perceptron(x_train,y_train,same_weight= False)
print(weight)



Streaming output truncated to the last 5000 lines.
[0.1 0.3 0.2 0.2]
epoch 9106
[0.1 0.3 0.2 0.2]
epoch 9107
[0.1 0.3 0.2 0.2]
epoch 9108
[0.1 0.3 0.2 0.2]
epoch 9109
[0.1 0.3 0.2 0.2]
epoch 9110
[0.1 0.3 0.2 0.2]
epoch 9111
[0.1 0.3 0.2 0.2]
epoch 9112
[0.1 0.3 0.2 0.2]
epoch 9113
[0.1 0.3 0.2 0.2]
epoch 9114
[0.1 0.3 0.2 0.2]
epoch 9115
[0.1 0.3 0.2 0.2]
epoch 9116
[0.1 0.3 0.2 0.2]
epoch 9117
[0.1 0.3 0.2 0.2]
epoch 9118
[0.1 0.3 0.2 0.2]
epoch 9119
[0.1 0.3 0.2 0.2]
epoch 9120
[0.1 0.3 0.2 0.2]
epoch 9121
[0.1 0.3 0.2 0.2]
epoch 9122
[0.1 0.3 0.2 0.2]
epoch 9123
[0.1 0.3 0.2 0.2]
epoch 9124
[0.1 0.3 0.2 0.2]
epoch 9125
[0.1 0.3 0.2 0.2]
epoch 9126
[0.1 0.3 0.2 0.2]
epoch 9127
[0.1 0.3 0.2 0.2]
epoch 9128
[0.1 0.3 0.2 0.2]
epoch 9129
[0.1 0.3 0.2 0.2]
epoch 9130
[0.1 0.3 0.2 0.2]
epoch 9131
[0.1 0.3 0.2 0.2]
epoch 9132
[0.1 0.3 0.2 0.2]
epoch 9133
[0.1 0.3 0.2 0.2]
epoch 9134
[0.1 0.3 0.2 0.2]
epoch 9135
[0.1 0.3 0.2 0.2]
epoch 9136
[0.1 0.3 0.2 0.2]
epoch 9137
[0.1 0.3 0.2 0.2]
epo

KeyboardInterrupt: ignored