 NumPy program to create an array of 10 zeros,10 ones,
10 fives

In [ ]:
import numpy as np

In [ ]:
zeros = np.zeros(10)

In [ ]:
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
ones = np.ones(10)

In [ ]:
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
fives = np.ones(10)*5

In [ ]:
fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

 NumPy program to create an array of all the even
integers from 10 to 50

In [ ]:
even = np.arange(10,51,2)

In [ ]:
even

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

 NumPy program to generate a random number between 0 and
1

In [ ]:
rdm = np.random.rand(1)

In [ ]:
rdm

array([0.61589444])

In [ ]:
rdmint = np.random.randint(5,10)
rdmint

8

NumPy program to save the matrix (generated in question
3) to a text file and load it

In [ ]:
rdm = np.random.rand(3,3)

In [ ]:
np.savetxt('four.txt',rdm,fmt="%s")

In [ ]:
res = np.loadtxt('four.txt')

In [ ]:
res

array([[0.78228465, 0.3366613 , 0.04697933],
       [0.90271446, 0.48733179, 0.40710644],
       [0.47335768, 0.37756499, 0.81060857]])

#Panda


In [ ]:
import pandas as pd
from PIL import Image


 python program to read an image and save the image as a
matrix to a .csv file using pandas

In [ ]:
image = Image.open('anonymous.jpg')

In [ ]:
img_array = np.array(image)
img_array
img_array.shape

(1080, 1920, 3)

In [ ]:
arr = np.array(image.getdata())

In [ ]:
arr
arr.shape

(2073600, 3)

In [ ]:
df = pd.DataFrame(arr)

In [ ]:
df

0  1  2
0        0  2  1
1        0  2  1
2        0  2  1
3        0  2  1
4        0  2  1
...     .. .. ..
2073595  1  1  1
2073596  1  1  1
2073597  1  1  1
2073598  1  1  1
2073599  1  1  1

[2073600 rows x 3 columns]

In [ ]:
df.to_csv("output.csv")

program to import excel data from the .csv file
(generated in question 1) by excluding the last row and last
column

In [ ]:
df = pd.read_csv('output.csv')
print(df)

         Unnamed: 0  0  1  2
0                 0  0  2  1
1                 1  0  2  1
2                 2  0  2  1
3                 3  0  2  1
4                 4  0  2  1
...             ... .. .. ..
2073595     2073595  1  1  1
2073596     2073596  1  1  1
2073597     2073597  1  1  1
2073598     2073598  1  1  1
2073599     2073599  1  1  1

[2073600 rows x 4 columns]


In [ ]:
df.iloc[:-1,:-1]

Unnamed: 0  0  1
0                 0  0  2
1                 1  0  2
2                 2  0  2
3                 3  0  2
4                 4  0  2
...             ... .. ..
2073594     2073594  1  1
2073595     2073595  1  1
2073596     2073596  1  1
2073597     2073597  1  1
2073598     2073598  1  1

[2073599 rows x 3 columns]

In [ ]:
df

Unnamed: 0  0  1  2
0                 0  0  2  1
1                 1  0  2  1
2                 2  0  2  1
3                 3  0  2  1
4                 4  0  2  1
...             ... .. .. ..
2073595     2073595  1  1  1
2073596     2073596  1  1  1
2073597     2073597  1  1  1
2073598     2073598  1  1  1
2073599     2073599  1  1  1

[2073600 rows x 4 columns]

Pandas program to create the today's date

In [ ]:
now = pd.to_datetime("now")
print(now)

2021-08-09 04:35:18.530684


#part 3

In [ ]:
from datetime import date

def findAge(dob):
  today = date.today()
  return today.year-dob.year - ((today.month,today.day)< ( dob.month,dob.day))
 
print(findAge(date(2000,9,13))) 

20
