In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from sklearn.datasets import load_wine
data = load_wine()

In [ ]:
yactual = np.array(data['target'])
xdata = np.array(data['data'])


In [ ]:
# normalization
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(xdata)
xdata = scaler.transform(xdata)


In [ ]:
#shuffling
from sklearn.utils import shuffle
xdata,yactual = shuffle(xdata,yactual)

In [ ]:
#data splitting
from sklearn.model_selection import train_test_split
import random
xtrain,xtest,ytrain,ytest = train_test_split(xdata,yactual,test_size= 0.3)
xtest,xvalid,ytest,yvalid = train_test_split(xtest,ytest,test_size= 0.14)
print(xtrain.shape)
print(xvalid.shape)
print(xtest.shape)

(124, 13)
(8, 13)
(46, 13)


In [ ]:
#kfold
from sklearn.model_selection import KFold
def Kfold(xdata,yactual):
  kf = KFold(n_splits = 5, random_state=1000, shuffle = True)
  kf.get_n_splits(xdata)
  x_train = []
  x_test = []
  y_train = []
  y_test = []

  for train_index ,test_index in kf.split(xdata):
    xtr,xte = xdata[train_index],xdata[test_index]
    ytr,yte = yactual[train_index],yactual[test_index]
    x_train.append(xtr)
    x_test.append(xte)
    y_train.append(ytr)
    y_test.append(yte)

  x_train,x_test,y_train,y_test = np.array(x_train),np.array(x_test),np.array(y_train),np.array(y_test)

  return x_train,x_test,y_train,y_test


In [ ]:
x_train,x_test,y_train,y_test = Kfold(xdata,yactual)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray


In [ ]:
print(x_train)
print(x_test)
print(y_train)
print(y_test)

In [ ]:
#one hot encoding
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

def onehotencoding(y):
  label_encoder = LabelEncoder()
  integer_encoded = label_encoder.fit_transform(y)
  onehot_encoder = OneHotEncoder(sparse=False)
  integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
  onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
  return onehot_encoded

In [ ]:
ydata = onehotencoding(yactual)
print(ydata)

In [ ]:
def intercept(x):
  x0 = np.ones((x.shape[0],1))
  # print(x0)
  # print(np.concatenate((x0,x),axis = 1))
  return np.concatenate((x0,x),axis = 1)
  

In [ ]:
x0 = intercept(xdata)
print(x0)

[[1.         0.35263158 0.17588933 ... 0.33333333 0.55311355 0.04564907]
 [1.         0.5        0.60474308 ... 0.44715447 0.82417582 0.35092725]
 [1.         0.61315789 0.35968379 ... 0.17886179 0.43956044 0.35805991]
 ...
 [1.         0.32105263 0.19565217 ... 0.42276423 0.6959707  0.16547789]
 [1.         0.37368421 0.45256917 ... 0.15447154 0.16849817 0.42938659]
 [1.         0.65526316 0.48023715 ... 0.33333333 0.28937729 0.17261056]]


In [ ]:
def loss(h, y):
  return sum(-y*np.log(h) - (1-y)*np.log(1-h))
  

In [ ]:
def mse(h, y):
  return (((h-y)**2).mean())/2
def mse_in_iter(h, y):
  return (sum((h-y)**2))/2

In [ ]:
def sigmoid(x):
  return 1/ 1+np.exp()